import { TableRow, TableSchema, ColumnToUpdate } from "./types";

export class Table {
  private rows: TableRow[] = [];
  //   private unique: Record<string, Record<string, string>> = {};

  constructor(public readonly name: string, public schema: TableSchema) {}

  /**
   * Ensures that all column names exist on the table, enforces PRIMARY key constraint
   * and validates all values according to their column's data type
   * @param columnNames The columns to insert into
   * @param values The values to be inserted
   */
  private validateValues(columnNames: string[], values: any[][]) {
    let hasPrimaryKey = false;

    columnNames.forEach((columnName, i) => {
      if (!this.schema.columns[columnName]) {
        throw new Error(
          `Column "${columnName}" does not exist in ${this.name}`
        );
      }

      hasPrimaryKey = hasPrimaryKey || this.schema.primaryKey === columnName;
    });

    if (!hasPrimaryKey) {
      // Throw error if the primary key column name is not among the provided column names
      // TODO: This behavior should change if primary key is autogenerated
      throw new Error(
        `NULL value in column ${this.schema.primaryKey} violates PRIMARY KEY constraint`
      );
    }

    const validRows: TableRow[] = [];

    values.forEach((valuesRow) => {
      const row: TableRow = {};

      valuesRow.forEach((value, i) => {
        const columnName = columnNames[i];
        if (!columnName) {
          throw new Error("Column count doesn't match value count");
        }
        row[columnName] = value;
      });

      validRows.push(row);
    });

    return validRows;
  }

  insert(columnNames: string[], values: any[]) {
    const validRows = this.validateValues(columnNames, values);
    this.rows.push(...validRows);
  }

  select(columnNames: string[], whereFn = (r: TableRow) => true): TableRow[] {
    const result: TableRow[] = [];

    this.rows.forEach((row) => {
      if (whereFn(row)) {
        const resultRow: TableRow = {};
        columnNames.forEach((columnName) => {
          if (!this.schema.columns[columnName]) {
            throw new Error(
              `Column "${columnName}" does not exist in ${this.name}`
            );
          }
          resultRow[columnName] = row[columnName];
        });
        result.push(resultRow);
      }
    });

    return result;
  }

  update(columns: ColumnToUpdate[], whereFn = (r: TableRow) => true): number {
    // Validate columns
    columns.forEach((column) => {
      if (!this.schema.columns[column.column]) {
        throw new Error(
          `Column "${column.column}" does not exist in ${this.name}`
        );
      }
    });

    let rowsAffected = 0;

    this.rows.forEach((row) => {
      if (whereFn(row)) {
        columns.forEach((column) => {
          row[column.column] = column.value;
        });
        rowsAffected++;
      }
    });

    return rowsAffected;
  }

  delete(whereFn = (r: TableRow) => true): number {
    let rowsAffected = 0;

    this.rows = this.rows.filter((row) => {
      if (whereFn(row)) {
        rowsAffected++;
        return false;
      }
      return true;
    });

    return rowsAffected;
  }
}
